// Generated by https://quicktype.io

export interface FoodItem {
  id: number;
  name: string;
  description: string | null;
  is_raw: boolean;
  image_url: string;
  kcal: number | null;
  water: number | null;
  protein: number | null;
  fat: number | null;
  carbohydrate: number | null;
  fiber: number | null;
  alcohol: number | null;
  created_at: string;
  updated_at: string;
  categories: Category[];
  food_regions: FoodRegion[];
}

export interface Category {
  id: number;
  name: CategoryName;
  description: string | null;
  created_at: string;
  updated_at: string;
  pivot: Pivot;
}

export enum CategoryName {
  Carrot = "Carrot",
  Citrus = "Citrus",
  Fruit = "Fruit",
  Vegetable = "Vegetable",
}

export interface Pivot {
  food_id: number;
  category_id: number;
}

export interface FoodRegion {
  id: number;
  country_region_id: number;
  food_id: number;
  local_name: string;
  grows_in_region: boolean;
  created_at: string | null;
  updated_at: string | null;
  seasons: Season[];
  region: Region;
}

export interface Region {
  id: number;
  name: string;
  local_name: string;
  country_code: CountryCode;
  is_entire_country: boolean;
  created_at: string;
  updated_at: string;
  country?: Country;
}

export interface Country {
  code: CountryCode;
  name: CountryCode;
  local_name: string | null;
}

export enum CountryCode {
  Fr = "fr",
  Pl = "pl",
}

export interface Season {
  id: number;
  start_date: string;
  month: number;
  month_name: MonthName;
  food_region_id: number;
  created_at: string;
  updated_at: string;
}

export enum MonthName {
  January = "January",
  February = "February",
  March = "March",
  April = "April",
  May = "May",
  June = "June",
  July = "July",
  August = "August",
  September = "September",
  October = "October",
  November = "November",
  December = "December",
}
